### ISSUE TITLE
[BUG] Handle Broken Pipe to enable use of `head` or `tail` without Error Message

### ISSUE THREAD

**Issue by AlJohri** [browser-history/browser-history#281]
**Describe the bug**
Pipeing the output of `browser-history` to head or tail prints a `BrokenPipeError`.

**To Reproduce**

```
❯ browser-history -b Firefox | head -n 1
Timestamp,URL,Title
Traceback (most recent call last):
  File "/Users/aljohri/.local/share/mise/installs/python/3.9.16/bin/browser-history", line 8, in <module>
    sys.exit(main())
  File "/Users/aljohri/.local/share/mise/installs/python/3.9.16/lib/python3.9/site-packages/browser_history/cli.py", line 218, in main
    cli(sys.argv[1:])
  File "/Users/aljohri/.local/share/mise/installs/python/3.9.16/lib/python3.9/site-packages/browser_history/cli.py", line 208, in cli
    print(outputs.formatted(args.format))
BrokenPipeError: [Errno 32] Broken pipe
```

**Expected behavior**
I expect to pipe the command to `head` and not see the `BrokenPipeError`.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - `browser-history`: 0.4.1
 - Python version: 3.9.16

**Additional context**

I think you can add a try except to catch the [BrokenPipeError](https://docs.python.org/3/library/exceptions.html#BrokenPipeError) and handle it without printing the error message.

**Comment by ObaraEmmanuel** [comment]
@AlJohri Thanks for reporting the issue. After some experimentation, there indeed is some issue with the unhandled `BrokenPipeError`. I will patch it as soon as possible.
